# Generated by Django 4.2.4 on 2025-10-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes_notes_privees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='contenu',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notes',
            name='moyenne',
            field=models.FloatField(default=0),
        ),
    ]
